### ISSUE TITLE
Part.text in multiPartBody

### ISSUE THREAD

**Issue by Zeroman** [hsiafan/requests#11]
python的request有data参数，可以将参数放到body区，目前这个版本没有这个功能，不能将参数取放到body区，所以params是有长度限制的。这个功能好实现吗？

**Comment by ScienJus** [comment]
有吧

**Comment by clearthesky** [comment]
可以用forms这个方法设置，然后这个需要用POST来发送请求。

```java
Requests.post(url).forms(params).send()...
```
这样

**Comment by Zeroman** [comment]
`
RequestBuilder builder = Requests.post(baseUrl + "topic/create").params(params);
List<Map.Entry<String, String>> bodyParams = new ArrayList<>();
bodyParams.add(new AbstractMap.SimpleEntry("content", getPara("content")));
builder = builder.multiPartBody(parts);
String jsonStr = builder.send().readToText();
`
multiPartBody和body只能二选一，multiPartBody的时候就不行了，
multiPartBody的时候只有Part<file>有效，Part<String>是没有用的。

**Comment by Zeroman** [comment]
刚刚看了源码，发现这样可以搞定：
parts.add(Part.file("content", null, getPara("content").getBytes()).contentType(""));
有的服务端解析上传文件的时候，根据filename字段判断。当filename为null的时候，可以和文件区分开来。
但是Part.text为什么没有放到part区域，而是直接放到了first_boundary，不解。

**Comment by clearthesky** [comment]
是除了那些参数请求还有文件之类的多个内容要POST上去?
MultiPart 其实就是把多个不同的body合并成一个，然后中间用分隔符隔开，你这种需求应该就是要part进去吧。

但是Part.text为什么没有放到part区域，而是直接放到了first_boundary，这个是指?

**Comment by clearthesky** [comment]
我想我看懂你的意思了。。
你说的情况应该是这样的，就是比如上传一个文件file.jpg，然后还有几个参数，比如a=xxx, b=yyy，你是想要这样的一个Multi Part 请求:
```
--*****
Content-Disposition: form-data; name="a"

xx
--*****
Content-Disposition: form-data; name="b"

yy
--*****
Content-Disposition: form-data; name="file"; filename="file.jpg"
Content-Type: application/octet-stream

{file content}

--*****--
```
现在代码里的Part.text确实不是干这个的，它是加一个text类型的part进去。
而且现在也确实没有方便的接口实现这个需求，我想想怎么改一下，增加这块功能。

**Comment by Zeroman** [comment]
form如果可以加到 multiPartBody处理。处理body能合并使用。
builder.multiPartBody(parts).form(params)。

**Comment by Zeroman** [comment]
Part.param("key", "value")(包括Part.text的body)没有写入到发送的body当中，抓包看不到Part.param的内容，看起来好像是StringRequestBody在multiPartBody下写入不正常。

**Comment by clearthesky** [comment]
中间重构引入了bug导致还没有输出完就关闭了outputstream, 4.8.1 修复了这个问题
