### ISSUE TITLE
RawResponse类的getCookies方法获取cookie不全

### ISSUE THREAD

**Issue by Jiramew** [hsiafan/requests#19]
非常感谢您的开源，真的很好用。下面是我使用中遇到的一个问题(maven，4.14.0)~                  

1、
```{java}
rawRes = this.session.get(url).........send();
rawRes.getCookies();
```    
2、
调试时看到context.cookieJar.cookieMap中的cookie。

通过1、2两个地方看到的cookie数量是不对应的。如下图：

![1t ngco6u0 e1z f5rze](https://user-images.githubusercontent.com/5498332/32537020-dfd3c8c6-c49b-11e7-8de9-02c990867da9.png)

想请问一下获取cookie应该如何获取比较好~
非常感谢您~

**Comment by hsiafan** [comment]
rawRes.getCookies() 获得的只是这次response返回的cookie，Context里面维护了session里所有response返回的cookie。
这里看到context里面的cookie比response里拿到的多应该是这个原因。

**Comment by Jiramew** [comment]
原来是这样，确实，这个url自己会302跳转一次。多谢~
还想问一下如何能拿到context内的cookie呢？我试过反射可是没弄出来>.<

**Comment by hsiafan** [comment]
嗯，现在没有API可以拿到session里维护的cookie。
就目前来说，如果需要这个cookie可以先禁用followRedirect，自己处理，这样两个response里的cookie都可以拿到

**Comment by Jiramew** [comment]
嗯嗯，多谢您~已经拿到了~再次感谢~o(≧ω≦)o
