### ISSUE TITLE
不支持PATCH方法

### ISSUE THREAD

**Issue by kaixinbaba** [hsiafan/requests#33]
PATCH方法很少在项目中使用，最近我偶尔的机会要用到这个方法，看到虽然库里支持了patch的接口，但是仍然会返回invalid method PATCH
![image](https://user-images.githubusercontent.com/22809336/58015666-697ca800-7b2e-11e9-9110-80946023b3e3.png)

**Comment by hsiafan** [comment]
原因底层使用的是HttpURLConnection，HttpURLConnection一直都不支持Patch方法。目前没有好的解决方法

**Comment by kaixinbaba** [comment]
好的～还是感谢大佬
